export const SERVICE_LABELS_FR: Record<string, string> = {
  plomberie: 'Plomberie',
  electricite: 'Électricité',
  menuiserie: 'Menuiserie',
  peinture: 'Peinture',
  chauffage: 'Chauffage',
  climatisation: 'Climatisation',
  toiture: 'Toiture',
  renovation: 'Rénovation',
  jardinage: 'Jardinage',
  menage: 'Ménage',
  demenagement: 'Déménagement',
  montage_meubles: 'Montage de meubles',
  nettoyage: 'Nettoyage',
  livraison: 'Livraison',
  coursier: 'Coursier',
  chauffeur: 'Chauffeur',
  remorquage: 'Remorquage',
  informatique: 'Informatique',
  reparation_tech: 'Réparation tech',
  aide_informatique: 'Aide informatique',
  photo_video: 'Photo / vidéo',
  graphisme: 'Graphisme',
  tutorat: 'Tutorat',
  cours_particuliers: 'Cours particuliers',
  garderie: 'Garderie',
  aide_personnes_agees: 'Aide aux aînés',
  promenade_animaux: 'Promenade animaux',
  garde_animaux: 'Garde animaux',
  serveur: 'Serveur',
  barman: 'Barman',
  securite: 'Sécurité',
  animateur: 'Animateur',
  dj: 'DJ',
  manutention: 'Manutention',
  aide_menagere: 'Aide ménagère',
  bricolage: 'Bricolage',
  portage: 'Portage',
  peinture_artistique: 'Peinture artistique',
  couture: 'Couture',
  decoration: 'Décoration',
  autre: 'Autre',
};

export function serviceLabelFr(serviceType: string): string {
  return SERVICE_LABELS_FR[serviceType] ?? serviceType;
}
